import type { Tutorial } from "@/types"

export const extendedTutorials: Tutorial[] = [
  {
    id: "6", slug: "midjourney-beginners",
    title: "Midjourney 从零到精通 — 用嘴画画的 AI 神器",
    description: "零基础学会 Midjourney，从注册到出图，30 分钟画出一张能商用插画",
    tool: "Midjourney", toolIcon: "🎨", category: "ai-image" as any, difficulty: "beginner", estimatedTime: "30 分钟", updatedAt: "2026-06-02", readCount: 8765,
    tags: ["#Midjourney", "#AI绘画", "#新手入门"], content: "",
    prerequisites: ["能上外网", "Discord 账号", "对美感有基本判断"],
    suitable: ["想做自媒体的创作者", "需要配图的设计师", "对AI绘画好奇的普通人"],
    notSuitable: ["完全不想用英文输入的用户"],
    relatedTutorials: ["chatgpt-beginners", "prompt-engineering", "stable-diffusion"],
  },
  {
    id: "7", slug: "stable-diffusion",
    title: "Stable Diffusion 本地部署 — 免费 AI 绘画，想画多少画多少",
    description: "在自己电脑上装 Stable Diffusion，永久免费。从安装模型到出图调参，一篇讲透",
    tool: "Stable Diffusion", toolIcon: "🖼️", category: "ai-image" as any, difficulty: "intermediate", estimatedTime: "2 小时", updatedAt: "2026-06-02", readCount: 6543,
    tags: ["#StableDiffusion", "#AI绘画", "#开源", "#本地部署"], content: "",
    prerequisites: ["NVIDIA 显卡（至少 4G 显存）", "会复制粘贴命令行", "硬盘预留 20G 空间"],
    suitable: ["想免费不限量出图的用户", "需要高度定制化的创作者", "隐私敏感的艺术家"],
    notSuitable: ["没有独立显卡的用户", "不想折腾环境的小白"],
    relatedTutorials: ["midjourney-beginners", "prompt-engineering"],
  },
  {
    id: "8", slug: "cursor-beginners",
    title: "Cursor 零基础入门 — 2026 年最火的 AI 编程 IDE",
    description: "从安装到写项目，手把手教你用 Cursor。不用记语法，说人话就能写代码",
    tool: "Cursor", toolIcon: "🖱️", category: "ai-coding" as any, difficulty: "beginner", estimatedTime: "45 分钟", updatedAt: "2026-06-02", readCount: 12345,
    tags: ["#Cursor", "#AI编程", "#IDE", "#零基础"], content: "",
    prerequisites: ["电脑（Mac/Windows/Linux 都行）", "会用浏览器下载软件"],
    suitable: ["完全没写代码的新手", "想用 AI 写个小工具的职场人", "前端开发者"],
    notSuitable: ["习惯 JetBrains 的硬核程序员"],
    relatedTutorials: ["claude-code", "codex-beginners", "prompt-engineering"],
  },
  {
    id: "9", slug: "kimi-beginners",
    title: "Kimi 保姆级教程 — 国产长文本 AI 之王",
    description: "月之暗面出品，200 万字超长上下文。上传整本书分析、长文档总结不在话下",
    tool: "Kimi", toolIcon: "🌙", category: "ai-chat" as any, difficulty: "beginner", estimatedTime: "20 分钟", updatedAt: "2026-06-02", readCount: 5678,
    tags: ["#Kimi", "#月之暗面", "#长文本", "#国产AI"], content: "",
    prerequisites: ["手机号（国内可注册）", "能上网的设备"],
    suitable: ["需要分析大量文档的研究者", "法律/金融专业看长文本的人", "不想花钱用 AI 的学生"],
    notSuitable: ["需要多模态（图片生成）的用户"],
    relatedTutorials: ["deepseek-beginners", "chatgpt-beginners", "prompt-engineering"],
  },
  {
    id: "10", slug: "gemini-beginners",
    title: "Google Gemini 入门指南 — 多模态 AI 的天花板",
    description: "Google 的 AI 能看懂图片、听懂语音、分析视频。教你用好这个全能选手",
    tool: "Gemini", toolIcon: "🔮", category: "ai-chat" as any, difficulty: "beginner", estimatedTime: "30 分钟", updatedAt: "2026-06-02", readCount: 4567,
    tags: ["#Gemini", "#Google", "#多模态", "#免费"], content: "",
    prerequisites: ["Google 账号（Gmail 就行）", "部分功能需科学上网"],
    suitable: ["已有 Google 生态的用户", "需要多模态能力的用户"],
    notSuitable: ["国内纯中文环境用户"],
    relatedTutorials: ["chatgpt-beginners", "deepseek-beginners"],
  },
  {
    id: "11", slug: "ai-video-tools",
    title: "AI 生成视频工具大盘点 — Sora/可灵/Runway 谁最强",
    description: "文生视频、图生视频、视频剪辑。2026 年 AI 视频工具横评",
    tool: "AI 视频", toolIcon: "🎬", category: "ai-video" as any, difficulty: "beginner", estimatedTime: "40 分钟", updatedAt: "2026-06-02", readCount: 7890,
    tags: ["#AI视频", "#Sora", "#可灵", "#Runway"], content: "",
    prerequisites: ["对视频制作有基本概念", "部分工具需付费"],
    suitable: ["短视频创作者", "想做 AI 视频号的人", "广告/营销从业者"],
    notSuitable: ["完全零预算的用户"],
    relatedTutorials: ["midjourney-beginners", "ai-audio-tools"],
  },
  {
    id: "12", slug: "ai-audio-tools",
    title: "AI 音频工具全攻略 — 语音克隆/配音/音乐生成",
    description: "用 AI 克隆自己的声音、生成背景音乐、做播客。覆盖 Suno/ElevenLabs/剪映配音",
    tool: "AI 音频", toolIcon: "🎵", category: "ai-audio" as any, difficulty: "beginner", estimatedTime: "35 分钟", updatedAt: "2026-06-02", readCount: 3456,
    tags: ["#AI音频", "#Suno", "#语音克隆", "#播客"], content: "",
    prerequisites: ["对音频有兴趣就行", "部分工具需注册账号"],
    suitable: ["想做播客的人", "视频创作者需要配音的", "音乐爱好者"],
    notSuitable: ["需要专业级音质的音乐制作人"],
    relatedTutorials: ["ai-video-tools", "chatgpt-beginners"],
  },
  {
    id: "13", slug: "ai-writing-tools",
    title: "AI 写作工具哪家强 — Claude vs ChatGPT vs Notion AI 实测对比",
    description: "写文案、写小说、写周报。从 3 个维度测评主流 AI 写作工具，附 Prompt 模板",
    tool: "AI 写作", toolIcon: "✍️", category: "ai-writing" as any, difficulty: "beginner", estimatedTime: "40 分钟", updatedAt: "2026-06-02", readCount: 11000,
    tags: ["#AI写作", "#文案", "#NotionAI", "#对比"], content: "",
    prerequisites: ["使用过至少一款 AI", "有写作需求就行"],
    suitable: ["自媒体人", "运营/市场人", "想用AI写小说的", "每天要写周报的职场人"],
    notSuitable: ["只写代码不写文档的程序员"],
    relatedTutorials: ["chatgpt-beginners", "prompt-engineering"],
  },
  {
    id: "14", slug: "notion-ai",
    title: "Notion AI 终极指南 — 笔记+AI 的完美结合",
    description: "在 Notion 里直接使用 AI。写会议纪要、生成数据库、翻译文档，一个工具全搞定",
    tool: "Notion AI", toolIcon: "📝", category: "ai-writing" as any, difficulty: "beginner", estimatedTime: "25 分钟", updatedAt: "2026-06-02", readCount: 6789,
    tags: ["#Notion", "#AI写作", "#效率工具", "#笔记"], content: "",
    prerequisites: ["Notion 账号（免费即可）", "愿意每月花 $10 升级 AI 功能"],
    suitable: ["Notion 用户", "需要 AI 辅助写作和整理的人", "团队协作场景"],
    notSuitable: ["不用 Notion 的人", "预算敏感的个人用户"],
    relatedTutorials: ["ai-writing-tools", "chatgpt-beginners"],
  },
  {
    id: "15", slug: "ai-ppt",
    title: "用 AI 做 PPT — 3 款工具让你告别加班做幻灯片",
    description: "输入一句话，AI 生成整份 PPT。实测 Gamma/AI PPT/美图 AI PPT",
    tool: "AI PPT", toolIcon: "📊", category: "ai-writing" as any, difficulty: "beginner", estimatedTime: "25 分钟", updatedAt: "2026-06-02", readCount: 15000,
    tags: ["#PPT", "#AI办公", "#效率", "#职场"], content: "",
    prerequisites: ["有做 PPT 的需求就行"],
    suitable: ["经常做汇报的职场人", "教师/培训师", "学生党（答辩 PPT）"],
    notSuitable: ["需要极致设计感的品牌发布会"],
    relatedTutorials: ["ai-writing-tools", "prompt-engineering"],
  },
  {
    id: "16", slug: "github-copilot",
    title: "GitHub Copilot 从安装到精通 — 程序员的 AI 副驾驶",
    description: "微软出品，在 VS Code 里自动补全代码。从安装到高阶用法，编码速度翻倍",
    tool: "GitHub Copilot", toolIcon: "🦾", category: "ai-coding" as any, difficulty: "beginner", estimatedTime: "30 分钟", updatedAt: "2026-06-02", readCount: 13456,
    tags: ["#Copilot", "#AI编程", "#微软", "#VS Code"], content: "",
    prerequisites: ["VS Code 或 JetBrains IDE", "GitHub 账号", "学生可免费申请"],
    suitable: ["所有程序员", "计算机专业学生", "用VS Code的开发者"],
    notSuitable: ["用不惯代码补全的老程序员"],
    relatedTutorials: ["cursor-beginners", "claude-code", "codex-beginners"],
  },
  {
    id: "17", slug: "rag-beginners",
    title: "AI 知识库搭建 — RAG 入门，让 AI 读懂你的文档",
    description: "手把手教你搭建私人 AI 知识库。上传公司文档、个人笔记，AI 精准回答",
    tool: "RAG", toolIcon: "🧠", category: "ai-agent" as any, difficulty: "intermediate", estimatedTime: "1.5 小时", updatedAt: "2026-06-02", readCount: 4567,
    tags: ["#RAG", "#知识库", "#Agent", "#进阶"], content: "",
    prerequisites: ["Python 基础", "了解什么是 API", "有一堆电子文档"],
    suitable: ["想建公司内部 AI 助手的", "有大量文档想被AI读的"],
    notSuitable: ["完全不会 Python 的小白"],
    relatedTutorials: ["prompt-engineering", "deepseek-beginners"],
  },
  {
    id: "18", slug: "ai-agent-beginners",
    title: "AI Agent 入门 — 让 AI 自己干活，帮你省时间",
    description: "什么是 Agent？和普通聊天 AI 有什么区别？5 个案例带你玩转 AI Agent",
    tool: "AI Agent", toolIcon: "🤖", category: "ai-agent" as any, difficulty: "beginner", estimatedTime: "40 分钟", updatedAt: "2026-06-02", readCount: 9876,
    tags: ["#Agent", "#自动化", "#AI工具", "#概念"], content: "",
    prerequisites: ["用过至少一款 AI 工具", "对自动化有兴趣"],
    suitable: ["想了解 AI 前沿的人", "想用 AI 自动完成工作流的人", "产品经理/创业者"],
    notSuitable: ["只把 AI 当聊天工具的用户"],
    relatedTutorials: ["claude-code", "codex-beginners", "rag-beginners"],
  },
  {
    id: "19", slug: "ai-excel",
    title: "AI + Excel 实战 — 数据分析不求人",
    description: "用 AI 处理 Excel 表格：公式生成、数据清洗、图表制作、VBA 宏",
    tool: "AI 办公", toolIcon: "📈", category: "ai-chat" as any, difficulty: "beginner", estimatedTime: "35 分钟", updatedAt: "2026-06-02", readCount: 18000,
    tags: ["#Excel", "#数据分析", "#AI办公", "#职场技能"], content: "",
    prerequisites: ["会用 Excel 打开文件", "有数据要分析"],
    suitable: ["经常处理 Excel 的职场人", "运营/财务/人事"],
    notSuitable: ["Excel 出神入化的用户"],
    relatedTutorials: ["ai-ppt", "prompt-engineering", "chatgpt-beginners"],
  },
  {
    id: "20", slug: "ai-seo-writing",
    title: "AI 写 SEO 文章 — 一天 10 篇高质量原创",
    description: "用 AI 批量写 SEO 优化文章。从关键词研究到发布，全流程 SOP + Prompt 模板",
    tool: "AI 写作", toolIcon: "🔍", category: "ai-writing" as any, difficulty: "intermediate", estimatedTime: "45 分钟", updatedAt: "2026-06-02", readCount: 6789,
    tags: ["#SEO", "#内容创作", "#AI写作", "#流量"], content: "",
    prerequisites: ["有一个网站或博客", "了解什么是 SEO"],
    suitable: ["独立博主", "做 SEO 的运营", "内容营销从业者"],
    notSuitable: ["对 SEO 完全不感兴趣的人"],
    relatedTutorials: ["prompt-engineering", "ai-writing-tools"],
  },
]

export const extendedTutorialContents: Record<string, string[]> = {
  "midjourney-beginners": [
    "### 第一步：注册 Discord 和 Midjourney",
    "Midjourney 寄生在 Discord 上，先去 discord.com 注册账号",
    "然后去 midjourney.com 官网 → Join Beta → 加入 Discord 服务器",
    "在 Discord 左侧找到 #newbies-xx 频道（有很多个，随便选一个）",
    "在输入框输入 /imagine 然后按 Tab 或空格，输入你的 Prompt",
    "> 小提示：免费版有 25 次额度，用完后需订阅（$10/月起）",
    "",
    "### 第二步：画出第一张图",
    "输入 /imagine a cute cat sitting on a cloud, digital art style --ar 4:3",
    "等待 1-2 分钟，Midjourney 会生成 4 张图让你选择",
    "U1-U4 = 放大对应的某一张图（Upscale）",
    "V1-V4 = 基于某一张图生成 4 个变体（Variation）",
    "",
    "### 第三步：Prompt 公式",
    "标准公式：主体 + 细节描述 + 风格 + 光照 + 视角 + 参数",
    "例：a Chinese girl in hanfu, in ancient temple, cherry blossoms, cinematic lighting, photorealistic, 8k --ar 16:9",
    "也可以用中文描述，MJ 会自动翻译",
    "",
    "### 第四步：参数速查",
    "--ar 宽高比（16:9 / 4:3 / 1:1 / 9:16）",
    "--stylize 艺术风格强度（0-1000 默认 100）",
    "--no 排除元素（--no text, watermark）",
    "--chaos 0-100 产出多样性",
    "",
    "### 第五步：实战案例",
    "公众号封面：a futuristic city skyline at night, neon lights, cyberpunk --ar 2:1",
    "产品图：a minimalist desk setup with macbook, coffee, plants, morning sunlight --ar 4:3",
    "小红书头像：a cute anime girl with blue eyes, pastel colors, soft lighting, portrait --ar 1:1",
    "",
    "### 进阶技巧",
    "垫图：上传图片 → 复制链接 → /imagine [链接] + prompt",
    "Blend：/blend 上传两张图混合",
    "多重 Prompt：cat::2 dog::1 猫权重是狗的两倍",
    "Remix Mode：设置里开启，V 变体时可以改 Prompt",
  ],
  "stable-diffusion": [
    "### 第一步：了解 Stable Diffusion",
    "开源免费，在自己电脑上跑，完全控制一切",
    "需要 NVIDIA 显卡（至少 4G 显存）",
    "没有显卡也可用 Google Colab 或云端服务",
    "",
    "### 第二步：安装 AUTOMATIC1111 WebUI",
    "前置条件：Python 3.10.6 + Git",
    "1. git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git",
    "2. cd stable-diffusion-webui",
    "3. 双击 webui-user.bat 启动",
    "4. 首次启动需要下载依赖，等 10-30 分钟",
    "5. 浏览器打开 http://127.0.0.1:7860",
    "",
    "### 第三步：下载模型",
    "模型 = 画风模板",
    "真实风格：ChilloutMix, Realistic Vision",
    "动漫风格：Anything V5, Counterfeit",
    "通用：DreamShaper, SDXL",
    "放到 models/Stable-diffusion/ 文件夹后刷新",
    "",
    "### 第四步：核心参数",
    "Prompt：正面提示词，描述你想要的",
    "Negative Prompt：不想出现的（bad hands, ugly, deformed）",
    "Sampling Steps：20-30 最佳",
    "CFG Scale：7 默认，越大越遵循 Prompt",
    "分辨率：从 512x512 开始",
    "",
    "### 第五步：img2img 和 Inpaint",
    "图生图：上传图片让 AI 重绘",
    "Denoising Strength 0.3-0.7 控制变化幅度",
    "Inpaint：涂黑区域局部重绘，修手修脸的利器",
    "",
    "### 第六步：ControlNet",
    "精确控制姿势、构图的最强插件",
    "OpenPose：控制人物姿态",
    "Canny：控制边缘线条",
    "Depth：控制景深和空间",
    "",
    "### 替代方案",
    "Google Colab：免费 T4 显卡",
    "云端：RunPod / AutoDL 按小时租",
    "在线版：PlaygroundAI, Leonardo.ai",
  ],
  "cursor-beginners": [
    "### 什么是 Cursor？",
    "基于 VS Code 改造的 AI 编程 IDE",
    "用中文描述，AI 帮你写代码",
    "2026 年最火的 AI 编程工具",
    "",
    "### 第一步：下载安装",
    "cursor.com → Download → 安装",
    "注册免费账号（每月 2000 次 AI 补全）",
    "可一键导入 VS Code 配置",
    "",
    "### 第二步：三种交互方式",
    "Tab：代码自动补全（最常用）",
    "Ctrl+K：选中代码 → 用自然语言改",
    "Ctrl+L：对话面板 → 问 AI 写什么",
    "Ctrl+I（Composer）：多文件同时编辑",
    "",
    "### 第三步：实战 — 写一个网页",
    "1. 新建文件夹，在 Cursor 打开",
    "2. Ctrl+I 输入：帮我创建个人名片网页，含姓名、简介、技能标签、深色模式",
    "3. Cursor 自动创建 HTML/CSS/JS 文件",
    "4. Accept All → 预览",
    "",
    "### 第四步：进阶技巧",
    "@file 引用特定文件",
    "@codebase 理解整个项目",
    ".cursorrules 告诉 AI 编码规范",
    "Debug：贴报错信息让 AI 分析",
    "",
    "### 和 Copilot 区别",
    "Cursor 更懂上下文，适合大改",
    "Copilot 补全更快，适合小改",
    "建议两个都装",
  ],
  "kimi-beginners": [
    "### Kimi 是什么？",
    "月之暗面（Moonshot）出品，国产长文本之王",
    "200 万字超长上下文，相当于一次读完整本《三体》",
    "完全免费，国内手机号注册即可",
    "",
    "### 第一步：注册",
    "kimi.moonshot.cn → 手机号注册",
    "支持网页版、微信小程序、iOS/Android",
    "",
    "### 第二步：上传文件",
    "点击 + 选择文件（PDF/Word/Excel/PPT/TXT）",
    "单文件最大 100MB",
    "上传后直接提问",
    "",
    "### 第三步：实战场景",
    "读论文：上传 PDF → 总结核心观点",
    "审合同：找出对我不利的条款",
    "面试准备：上传 JD → AI 模拟面试",
    "数据分析：上传 Excel → 分析趋势",
    "学习辅导：上传教材 → 划重点",
    "",
    "### 第四步：联网搜索",
    "手动开启联网按钮",
    "查新闻、查政策、查实时数据",
    "",
    "### Kimi vs DeepSeek",
    "Kimi：长文档王者",
    "DeepSeek：通用更强",
    "建议都有，按需切换",
  ],
  "gemini-beginners": [
    "### Gemini 是什么？",
    "Google 的多模态 AI，完全免费",
    "能看懂图片、听懂语音、分析视频",
    "有 Google 账号就能用",
    "",
    "### 第一步：开始使用",
    "gemini.google.com → 登录 Google 账号",
    "可能需要科学上网",
    "底部输入框直接输入",
    "",
    "### 第二步：多模态功能",
    "图片分析：拍植物照片问怎么养",
    "视频分析：粘贴 YouTube 链接总结",
    "音频识别：上传录音转文字",
    "文件分析：读取 Google Drive 文件",
    "",
    "### 第三步：实战案例",
    "旅行规划：日本 7 天预算 1 万，帮我规划",
    "拍题讲解：拍照让 AI 一步步教",
    "代码生成：给数据让 Gemini 写可视化代码",
    "翻译+解释：翻译合同并解释术语",
    "",
    "### Gemini vs ChatGPT",
    "Gemini 完全免费，多模态更强",
    "ChatGPT 编程和插件生态更好",
    "建议都试一下",
    "",
    "### 进阶",
    "Gemini Advanced $19.99/月 使用 Ultra 模型",
    "Gemini API 可自己做应用",
    "Workspace 集成：Gmail/Docs/Sheets 内使用",
  ],
  "ai-video-tools": [
    "### 2026 AI 视频工具格局",
    "三类工具：文生视频、图生视频、AI 剪辑",
    "",
    "### 可灵 AI（强烈推荐国内用户）",
    "kling.kuaishou.com → 免费，中文",
    "文生视频和图生视频都支持",
    "画质不错，中国风场景效果好",
    "每天免费额度够用",
    "",
    "### Runway（功能最全）",
    "runwayml.com → $15/月起",
    "Gen-3 Alpha 生成效果好",
    "Motion Brush 控制物体运动",
    "适合做广告片",
    "",
    "### Pika（最简单）",
    "pika.art → $10/月起",
    "界面简洁，零基础友好",
    "局部修改功能很实用",
    "",
    "### Sora（质量最高）",
    "OpenAI 出品，还在公测",
    "真实感所有工具最强",
    "预计 $20/月",
    "",
    "### Prompt 技巧",
    "描述要详细：穿着红色汉服的女孩在樱花树下跳舞",
    "加风格：电影感、纪录片、动画风",
    "控制镜头：zoom in / zoom out / camera orbit",
    "",
    "### 新手路线",
    "第一周：可灵免费体验",
    "第二周：做 5 个短视频发小红书",
    "第三周：尝试 Runway 图生视频",
    "第四周：剪映 AI 功能做完整视频",
  ],
  "ai-audio-tools": [
    "### AI 音频三大类",
    "语音合成（TTS）：文字转语音",
    "音乐生成：AI 作曲写歌",
    "语音克隆：复制特定声音",
    "",
    "### 剪映 — 免费配音",
    "文字转语音，几十种主播声音",
    "有东北话、四川话、粤语方言",
    "手机和电脑版都免费",
    "",
    "### Suno AI — 写歌神器",
    "suno.ai → 注册（每日免费 5 首）",
    "输入歌词描述：一首轻快的民谣",
    "或让 AI 自动写词",
    "30 秒生成完整歌曲",
    "$10/月可商用",
    "",
    "### ElevenLabs — 语音克隆",
    "elevenlabs.io → 免费克隆 3 个声音",
    "上传 3 分钟声音样本",
    "任意文字用这个声音朗读",
    "情感控制、语速调节",
    "中文效果很好",
    "",
    "### 应用场景",
    "短视频配音：剪映就够了",
    "播客音乐：Suno 生成 BGM",
    "有声书：ElevenLabs 克隆声音朗读",
    "AI 数字人：ElevenLabs 实时语音",
    "",
    "### 新手推荐",
    "先玩剪映配音，零成本",
    "再试 Suno 生成音乐，很惊艳",
    "最后研究 ElevenLabs",
  ],
};
