import type { Tutorial } from "@/types"

export const extendedTutorials: Tutorial[] = [
  {
    id: "6", slug: "midjourney-beginners",
    title: "Midjourney 从零到精通 — 用嘴画画的 AI 神器",
    description: "零基础学会 Midjourney，从注册到出图，30 分钟画出一张能商用插画",
    tool: "Midjourney", toolIcon: "🎨", category: "ai-image" as any, difficulty: "beginner", estimatedTime: "30 分钟", updatedAt: "2026-06-02", readCount: 8765,
    tags: ["#Midjourney", "#AI绘画", "#新手入门"], content: "",
    prerequisites: ["能上外网", "Discord 账号", "对美感有基本判断"],
    suitable: ["想做自媒体的创作者", "需要配图的设计师", "对AI绘画好奇的普通人"],
    notSuitable: ["完全不想用英文输入的用户"],
    relatedTutorials: ["chatgpt-beginners", "prompt-engineering", "stable-diffusion"],
  },
  {
    id: "7", slug: "stable-diffusion",
    title: "Stable Diffusion 本地部署 — 免费 AI 绘画，想画多少画多少",
    description: "在自己电脑上装 Stable Diffusion，永久免费。从安装模型到出图调参，一篇讲透",
    tool: "Stable Diffusion", toolIcon: "🖼️", category: "ai-image" as any, difficulty: "intermediate", estimatedTime: "2 小时", updatedAt: "2026-06-02", readCount: 6543,
    tags: ["#StableDiffusion", "#AI绘画", "#开源", "#本地部署"], content: "",
    prerequisites: ["NVIDIA 显卡（至少 4G 显存）", "会复制粘贴命令行", "硬盘预留 20G 空间"],
    suitable: ["想免费不限量出图的用户", "需要高度定制化的创作者", "隐私敏感的艺术家"],
    notSuitable: ["没有独立显卡的用户", "不想折腾环境的小白"],
    relatedTutorials: ["midjourney-beginners", "prompt-engineering"],
  },
  {
    id: "8", slug: "cursor-beginners",
    title: "Cursor 零基础入门 — 2026 年最火的 AI 编程 IDE",
    description: "从安装到写项目，手把手教你用 Cursor。不用记语法，说人话就能写代码",
    tool: "Cursor", toolIcon: "🖱️", category: "ai-coding" as any, difficulty: "beginner", estimatedTime: "45 分钟", updatedAt: "2026-06-02", readCount: 12345,
    tags: ["#Cursor", "#AI编程", "#IDE", "#零基础"], content: "",
    prerequisites: ["电脑（Mac/Windows/Linux 都行）", "会用浏览器下载软件"],
    suitable: ["完全没写代码的新手", "想用 AI 写个小工具的职场人", "前端开发者"],
    notSuitable: ["习惯 JetBrains 的硬核程序员"],
    relatedTutorials: ["claude-code", "codex-beginners", "prompt-engineering"],
  },
  {
    id: "9", slug: "kimi-beginners",
    title: "Kimi 保姆级教程 — 国产长文本 AI 之王",
    description: "月之暗面出品，200 万字超长上下文。上传整本书分析、长文档总结不在话下",
    tool: "Kimi", toolIcon: "🌙", category: "ai-chat" as any, difficulty: "beginner", estimatedTime: "20 分钟", updatedAt: "2026-06-02", readCount: 5678,
    tags: ["#Kimi", "#月之暗面", "#长文本", "#国产AI"], content: "",
    prerequisites: ["手机号（国内可注册）", "能上网的设备"],
    suitable: ["需要分析大量文档的研究者", "法律/金融专业看长文本的人", "不想花钱用 AI 的学生"],
    notSuitable: ["需要多模态（图片生成）的用户"],
    relatedTutorials: ["deepseek-beginners", "chatgpt-beginners", "prompt-engineering"],
  },
  {
    id: "10", slug: "gemini-beginners",
    title: "Google Gemini 入门指南 — 多模态 AI 的天花板",
    description: "Google 的 AI 能看懂图片、听懂语音、分析视频。教你用好这个全能选手",
    tool: "Gemini", toolIcon: "🔮", category: "ai-chat" as any, difficulty: "beginner", estimatedTime: "30 分钟", updatedAt: "2026-06-02", readCount: 4567,
    tags: ["#Gemini", "#Google", "#多模态", "#免费"], content: "",
    prerequisites: ["Google 账号（Gmail 就行）", "部分功能需科学上网"],
    suitable: ["已有 Google 生态的用户", "需要多模态能力的用户"],
    notSuitable: ["国内纯中文环境用户"],
    relatedTutorials: ["chatgpt-beginners", "deepseek-beginners"],
  },
  {
    id: "11", slug: "ai-video-tools",
    title: "AI 生成视频工具大盘点 — Sora/可灵/Runway 谁最强",
    description: "文生视频、图生视频、视频剪辑。2026 年 AI 视频工具横评",
    tool: "AI 视频", toolIcon: "🎬", category: "ai-video" as any, difficulty: "beginner", estimatedTime: "40 分钟", updatedAt: "2026-06-02", readCount: 7890,
    tags: ["#AI视频", "#Sora", "#可灵", "#Runway"], content: "",
    prerequisites: ["对视频制作有基本概念", "部分工具需付费"],
    suitable: ["短视频创作者", "想做 AI 视频号的人", "广告/营销从业者"],
    notSuitable: ["完全零预算的用户"],
    relatedTutorials: ["midjourney-beginners", "ai-audio-tools"],
  },
  {
    id: "12", slug: "ai-audio-tools",
    title: "AI 音频工具全攻略 — 语音克隆/配音/音乐生成",
    description: "用 AI 克隆自己的声音、生成背景音乐、做播客。覆盖 Suno/ElevenLabs/剪映配音",
    tool: "AI 音频", toolIcon: "🎵", category: "ai-audio" as any, difficulty: "beginner", estimatedTime: "35 分钟", updatedAt: "2026-06-02", readCount: 3456,
    tags: ["#AI音频", "#Suno", "#语音克隆", "#播客"], content: "",
    prerequisites: ["对音频有兴趣就行", "部分工具需注册账号"],
    suitable: ["想做播客的人", "视频创作者需要配音的", "音乐爱好者"],
    notSuitable: ["需要专业级音质的音乐制作人"],
    relatedTutorials: ["ai-video-tools", "chatgpt-beginners"],
  },
  {
    id: "13", slug: "ai-writing-tools",
    title: "AI 写作工具哪家强 — Claude vs ChatGPT vs Notion AI 实测对比",
    description: "写文案、写小说、写周报。从 3 个维度测评主流 AI 写作工具，附 Prompt 模板",
    tool: "AI 写作", toolIcon: "✍️", category: "ai-writing" as any, difficulty: "beginner", estimatedTime: "40 分钟", updatedAt: "2026-06-02", readCount: 11000,
    tags: ["#AI写作", "#文案", "#NotionAI", "#对比"], content: "",
    prerequisites: ["使用过至少一款 AI", "有写作需求就行"],
    suitable: ["自媒体人", "运营/市场人", "想用AI写小说的", "每天要写周报的职场人"],
    notSuitable: ["只写代码不写文档的程序员"],
    relatedTutorials: ["chatgpt-beginners", "prompt-engineering"],
  },
  {
    id: "14", slug: "notion-ai",
    title: "Notion AI 终极指南 — 笔记+AI 的完美结合",
    description: "在 Notion 里直接使用 AI。写会议纪要、生成数据库、翻译文档，一个工具全搞定",
    tool: "Notion AI", toolIcon: "📝", category: "ai-writing" as any, difficulty: "beginner", estimatedTime: "25 分钟", updatedAt: "2026-06-02", readCount: 6789,
    tags: ["#Notion", "#AI写作", "#效率工具", "#笔记"], content: "",
    prerequisites: ["Notion 账号（免费即可）", "愿意每月花 $10 升级 AI 功能"],
    suitable: ["Notion 用户", "需要 AI 辅助写作和整理的人", "团队协作场景"],
    notSuitable: ["不用 Notion 的人", "预算敏感的个人用户"],
    relatedTutorials: ["ai-writing-tools", "chatgpt-beginners"],
  },
  {
    id: "15", slug: "ai-ppt",
    title: "用 AI 做 PPT — 3 款工具让你告别加班做幻灯片",
    description: "输入一句话，AI 生成整份 PPT。实测 Gamma/AI PPT/美图 AI PPT",
    tool: "AI PPT", toolIcon: "📊", category: "ai-writing" as any, difficulty: "beginner", estimatedTime: "25 分钟", updatedAt: "2026-06-02", readCount: 15000,
    tags: ["#PPT", "#AI办公", "#效率", "#职场"], content: "",
    prerequisites: ["有做 PPT 的需求就行"],
    suitable: ["经常做汇报的职场人", "教师/培训师", "学生党（答辩 PPT）"],
    notSuitable: ["需要极致设计感的品牌发布会"],
    relatedTutorials: ["ai-writing-tools", "prompt-engineering"],
  },
  {
    id: "16", slug: "github-copilot",
    title: "GitHub Copilot 从安装到精通 — 程序员的 AI 副驾驶",
    description: "微软出品，在 VS Code 里自动补全代码。从安装到高阶用法，编码速度翻倍",
    tool: "GitHub Copilot", toolIcon: "🦾", category: "ai-coding" as any, difficulty: "beginner", estimatedTime: "30 分钟", updatedAt: "2026-06-02", readCount: 13456,
    tags: ["#Copilot", "#AI编程", "#微软", "#VS Code"], content: "",
    prerequisites: ["VS Code 或 JetBrains IDE", "GitHub 账号", "学生可免费申请"],
    suitable: ["所有程序员", "计算机专业学生", "用VS Code的开发者"],
    notSuitable: ["用不惯代码补全的老程序员"],
    relatedTutorials: ["cursor-beginners", "claude-code", "codex-beginners"],
  },
  {
    id: "17", slug: "rag-beginners",
    title: "AI 知识库搭建 — RAG 入门，让 AI 读懂你的文档",
    description: "手把手教你搭建私人 AI 知识库。上传公司文档、个人笔记，AI 精准回答",
    tool: "RAG", toolIcon: "🧠", category: "ai-agent" as any, difficulty: "intermediate", estimatedTime: "1.5 小时", updatedAt: "2026-06-02", readCount: 4567,
    tags: ["#RAG", "#知识库", "#Agent", "#进阶"], content: "",
    prerequisites: ["Python 基础", "了解什么是 API", "有一堆电子文档"],
    suitable: ["想建公司内部 AI 助手的", "有大量文档想被AI读的"],
    notSuitable: ["完全不会 Python 的小白"],
    relatedTutorials: ["prompt-engineering", "deepseek-beginners"],
  },
  {
    id: "18", slug: "ai-agent-beginners",
    title: "AI Agent 入门 — 让 AI 自己干活，帮你省时间",
    description: "什么是 Agent？和普通聊天 AI 有什么区别？5 个案例带你玩转 AI Agent",
    tool: "AI Agent", toolIcon: "🤖", category: "ai-agent" as any, difficulty: "beginner", estimatedTime: "40 分钟", updatedAt: "2026-06-02", readCount: 9876,
    tags: ["#Agent", "#自动化", "#AI工具", "#概念"], content: "",
    prerequisites: ["用过至少一款 AI 工具", "对自动化有兴趣"],
    suitable: ["想了解 AI 前沿的人", "想用 AI 自动完成工作流的人", "产品经理/创业者"],
    notSuitable: ["只把 AI 当聊天工具的用户"],
    relatedTutorials: ["claude-code", "codex-beginners", "rag-beginners"],
  },
  {
    id: "19", slug: "ai-excel",
    title: "AI + Excel 实战 — 数据分析不求人",
    description: "用 AI 处理 Excel 表格：公式生成、数据清洗、图表制作、VBA 宏",
    tool: "AI 办公", toolIcon: "📈", category: "ai-chat" as any, difficulty: "beginner", estimatedTime: "35 分钟", updatedAt: "2026-06-02", readCount: 18000,
    tags: ["#Excel", "#数据分析", "#AI办公", "#职场技能"], content: "",
    prerequisites: ["会用 Excel 打开文件", "有数据要分析"],
    suitable: ["经常处理 Excel 的职场人", "运营/财务/人事"],
    notSuitable: ["Excel 出神入化的用户"],
    relatedTutorials: ["ai-ppt", "prompt-engineering", "chatgpt-beginners"],
  },
  {
    id: "20", slug: "ai-seo-writing",
    title: "AI 写 SEO 文章 — 一天 10 篇高质量原创",
    description: "用 AI 批量写 SEO 优化文章。从关键词研究到发布，全流程 SOP + Prompt 模板",
    tool: "AI 写作", toolIcon: "🔍", category: "ai-writing" as any, difficulty: "intermediate", estimatedTime: "45 分钟", updatedAt: "2026-06-02", readCount: 6789,
    tags: ["#SEO", "#内容创作", "#AI写作", "#流量"], content: "",
    prerequisites: ["有一个网站或博客", "了解什么是 SEO"],
    suitable: ["独立博主", "做 SEO 的运营", "内容营销从业者"],
    notSuitable: ["对 SEO 完全不感兴趣的人"],
    relatedTutorials: ["prompt-engineering", "ai-writing-tools"],
  },
]

export const extendedTutorialContents: Record<string, string[]> = {
  "midjourney-beginners": [
    "### 第一步：注册 Discord 和 Midjourney",
    "Midjourney 寄生在 Discord 上，先去 discord.com 注册",
    "然后 midjourney.com → Join Beta → 加入 Discord 服务器",
    '找到 #newbies 频道，输入 /imagine + 你的 Prompt',
    "> 小提示：免费版 25 次额度用完需订阅（$10/月起）",
    "",
    "### 第二步：画出第一张图",
    '输入 /imagine a cute cat sitting on a cloud, digital art style --ar 4:3',
    "等 1-2 分钟，Midjourney 生成 4 张图",
    "U1-U4 放大对应图片，V1-V4 生成变体",
    "",
    "### 第三步：Prompt 公式",
    "主体 + 风格 + 光照 + 视角 + 参数",
    '例：a Chinese girl in hanfu, in ancient temple, cinematic lighting, photorealistic --ar 16:9',
    "",
    "### 第四步：进阶参数",
    "--ar 宽高比（16:9/4:3/1:1）",
    "--stylize 艺术风格强度（0-1000）",
    "--no 排除元素（--no text）",
  ],
  "stable-diffusion": [
    "### 第一步：安装 AUTOMATIC1111 WebUI",
    "1. 安装 Python 3.10 和 Git",
    "2. git clone AUTOMATIC1111/stable-diffusion-webui",
    "3. 运行 webui-user.bat（第一次等 10-20 分钟）",
    "4. 浏览器打开 http://127.0.0.1:7860",
    "",
    "### 第二步：下载模型",
    "动漫：Anything V5、Counterfeit",
    "真实人像：ChilloutMix、MajicMix",
    "通用：SDXL、DreamShaper",
    "放到 models/Stable-diffusion/ 文件夹",
    "",
    "### 第三步：核心参数",
    "Prompt + Negative Prompt",
    "Sampling Steps 20-30，CFG Scale 7",
    "分辨率从 512x512 起步",
    "",
    "### 进阶功能",
    "img2img：用图片做参考",
    "Inpaint：局部重绘",
    "ControlNet：精确控制姿态",
  ],
  "cursor-beginners": [
    "### 下载安装",
    "cursor.com → Download → 安装（3 分钟）",
    "注册免费账号（每月 2000 次 AI 补全）",
    "",
    "### 三种 AI 交互",
    "Tab 键：自动补全代码",
    "Ctrl+K：内联编辑（选中代码用自然语言改）",
    "Ctrl+L：对话面板（创建组件/写功能）",
    "",
    "### 实战：写一个 Todo App",
    "Ctrl+L 输入：帮我用 HTML+CSS+JS 写一个待办事项 App",
    "点 Apply → 代码自动写入文件",
    "",
    "### 进阶技巧",
    "@file 引用特定文件",
    "Cmd+Shift+I 对全项目提问",
    "Composer（Cmd+I）多文件同时编辑",
  ],
  "kimi-beginners": [
    "### 注册",
    "kimi.moonshot.cn → 手机号注册 → 微信登录",
    "完全免费，支持 200 万字上下文",
    "",
    "### 核心功能",
    "网页版对话：kimi.moonshot.cn",
    "上传文件：PDF/Word/PPT/Excel，单文件 100MB",
    "微信小程序搜 Kimi 智能助手",
    "浏览器插件：浏览网页时呼出 Kimi 总结",
    "",
    "### 最佳场景",
    "读论文：上传 PDF 让 Kimi 总结核心观点",
    "分析合同：检查对我不利的条款",
    "面试准备：上传 JD 让 Kimi 出面试题",
    "",
    "Kimi vs DeepSeek：Kimi 长文档王者，DeepSeek 通用强",
  ],
  "gemini-beginners": [
    "### 开始使用",
    "gemini.google.com → 登录 Google 账号 → 免费使用",
    "",
    "### 多模态体验",
    "上传图片分析：拍植物照片问怎么养",
    "分析视频：粘贴 YouTube 链接总结内容",
    "识别语音：录音直接发给 Gemini 分析",
    "",
    "### 实战案例",
    "旅行规划：我计划 7 月去日本 7 天，预算 1 万帮我规划",
    "学习辅导：拍数学题让 Gemini 一步步教你",
    "数据可视化：CSV 数据生成图表 Python 代码",
  ],
  "ai-video-tools": [
    "### 2026 AI 视频工具格局",
    "可灵：免费/中文友好（快手出品）",
    "Runway：$15/月/功能最全",
    "Pika：$10/月/简单易用",
    "Sora：$20/月/OpenAI 出品质量最高",
    "",
    "### 入门推荐：可灵",
    "搜索可灵 AI → 注册 → 输入中文描述 → 等 1-3 分钟生成",
    "",
    "### 进阶：Runway",
    "图生视频/视频编辑/风格迁移/Motion Brush",
    "新手从可灵开始，进阶玩 Runway",
  ],
  "ai-audio-tools": [
    "### Suno AI 音乐",
    "suno.ai → 注册（每日免费 5 首）",
    "输入歌词或让 AI 写 → 选风格 → 30 秒出歌",
    "",
    "### 语音克隆",
    "剪映：免费配音（图文成片功能）",
    "ElevenLabs：上传声音样本 → 克隆 → 任意文字用你的声音读",
    "",
    "### 适用场景",
    "短视频配音：剪映就够了",
    "播客音乐：Suno 免费生成",
    "有声书：ElevenLabs 克隆主播声音",
  ],
  "ai-writing-tools": [
    "### 四大 AI 写作工具对比",
    "文案创意：Claude > ChatGPT > DeepSeek",
    "中文能力：DeepSeek > Claude > ChatGPT",
    "长文质量：Claude 最强",
    "价格：DeepSeek 免费 / 其余 $10-20/月",
    "",
    "### 不同场景用什么",
    "写营销文案：Claude",
    "写周报：DeepSeek 免费好用",
    "笔记写作：Notion AI 集成方便",
    "中英翻译：DeepSeek 最自然",
    "",
    "### Prompt 模板",
    "小红书文案：你是小红书爆款文案专家，帮我写种草笔记...",
    "公众号文章：帮我写 [主题]，1500-2000 字，分 4-5 个小标题",
  ],
  "notion-ai": [
    "### 什么是 Notion AI",
    "Notion 内置 AI，记笔记时直接呼出不用切换 App",
    "开启：Any page → 空格键 → AI 菜单",
    "费用：$10/月（免费版无 AI）",
    "",
    "### 最实用功能",
    "会议纪要：选中笔记 → Summarize → 一键结构化",
    "翻译整页：中文笔记 → Translate → 英文",
    "头脑风暴：输入主题 → Brainstorm → 20 个点子",
    "数据库公式：用自然语言描述，AI 帮你写",
  ],
  "ai-ppt": [
    "### 三款 AI PPT 工具",
    "Gamma（gamma.app）：30 秒生成 PPT，免费版每月 10 份，最推荐",
    "AI PPT（aippt.cn）：国内产品，中文友好",
    "美图 AI PPT：模板好看，自动排版配图",
    "",
    "### 快速生成流程",
    "以 Gamma 为例：输入主题 → 选风格 → 30 秒生成 8 页",
    "不满意点 AI 调整 → 导出 PPTX/PDF",
    "提示：用 ChatGPT 先生成大纲再贴到 Gamma，效果更好",
  ],
  "github-copilot": [
    "### 安装",
    "VS Code 扩展商店搜 GitHub Copilot → 安装",
    "学生 edu 邮箱免费申请，个人 $10/月（30 天免费试用）",
    "",
    "### 基本用法",
    "代码补全：写代码时灰字提示 → Tab 接受",
    "注释生成代码：写好注释，Copilot 自动补全",
    "Ctrl+I 对话：选中代码用自然语言改",
    "",
    "### 高效技巧",
    "写好函数名和注释，Copilot 猜得更准",
    "打开多个关联文件，上下文更丰富",
    "不满意按 Alt+] 切换建议",
  ],
  "rag-beginners": [
    "### 什么是 RAG",
    "RAG = 检索增强生成。把文档切块 → 存向量数据库 → 提问时先检索再回答",
    '就像：一柜子书，AI 先查目录找到"第 3 本书第 45 页"，再回答你',
    "",
    "### 核心流程",
    "文档 → Embedding 转向量 → 存入向量数据库",
    "用户提问 → 转向量 → 检索最相似 → LLM 生成回答",
    "",
    "### 工具选型",
    "文档处理：LangChain 或 LlamaIndex",
    "向量数据库：Chroma（本地）或 Pinecone（云端）",
    "LLM：OpenAI API 或 DeepSeek API",
    "前端：Gradio 或 Streamlit",
  ],
  "ai-agent-beginners": [
    "### Agent 是什么",
    "普通 AI：你问 → AI 答 → 结束",
    "AI Agent：你给目标 → AI 规划步骤 → 执行 → 检查 → 调整 → 直到完成",
    "",
    "### Agent 核心能力",
    "工具调用：能写代码、查数据库、发邮件",
    "多步推理：拆成多个步骤执行",
    "记忆：记住上下文和决策",
    "自我纠错：做错了自己发现改正",
    "",
    "### 5 个 Agent 案例",
    "Claude Code/Codex CLI：AI 自动写+改+测试代码",
    "AutoGPT：给目标，24 小时不停跑",
    "数据分析 Agent：自动清洗→分析→画图→写报告",
    "客服 Agent：接入知识库自动回答",
    "定时新闻 Agent：每天自动抓新闻→总结→发邮件",
  ],
  "ai-excel": [
    "### AI + Excel 5 大场景",
    "生成公式：统计 A 列大于 100 的平均值 → AI 给 AVERAGEIFS",
    "数据清洗：B 列手机号统一格式为 138-0000-0000",
    "生成图表：用 A 列日期和 B 列销售额创建折线图",
    "写 VBA 宏：当 A 列超过 1000 自动标红整行",
    "数据分析报告：复制表格让 ChatGPT 分析趋势",
    "",
    "### 用什么 AI",
    "ChatGPT/DeepSeek：通用公式生成",
    "Claude：复杂 VBA 脚本",
    "WPS AI：国内 WPS 内置直接对话操作 Excel",
  ],
  "ai-seo-writing": [
    "### AI SEO 全流程",
    "关键词研究 → 生成大纲 → AI 写正文 → 优化内链 → 发布",
    "",
    "### 第一步：关键词研究",
    '让 AI 帮我找出 20 个 [AI 教程] 长尾关键词，月搜索量+竞争度',
    "",
    "### 第二步：生成大纲",
    '针对 [Kimi 怎么用] 写 2000 字大纲，含 5 个 H2',
    "",
    "### 第三步：写正文",
    "口语化科普风格，每段 150 字，配上生活类比",
    "",
    "### 第四步：SEO 优化",
    "加关键词变体 + meta description + FAQs",
    "核心原则：AI 写初稿，人工改 20%，Google 看重对用户有用",
  ],
}
