"use client"

import { useEffect, useState } from "react"

const tutorialContentMap: Record<string, string[]> = {
  "chatgpt-beginners": [
    "### 📝 第一步：注册账号",
    "",
    "1. 打开 ChatGPT 官网 chat.openai.com",
    "2. 点击 Sign up 按钮",
    "3. 输入邮箱地址（推荐 Gmail）",
    "4. 设置密码（至少 8 位）",
    "5. 验证邮箱（去邮箱里点确认链接）",
    "6. 输入手机号接收验证码",
    "7. 完成！开始使用",
    "",
    "> 💡 **小提示**：如果你有 Google 或 Microsoft 账号，可以直接用它们登录，省去注册步骤。",
    "",
    "### 🤔 第二步：第一次对话",
    "",
    "注册完成后，你会看到一个简洁的聊天界面。底部有一个输入框——这就是你和 ChatGPT 对话的地方。",
    "",
    "试试输入：",
    "> 用 100 字解释什么是 AI，让完全不懂技术的人也能听懂",
    "",
    "ChatGPT 会用流利的中文回答你。这个过程叫做流式输出——字会一个一个蹦出来，就像有人在打字给你看。",
    "",
    "### 🎯 第三步：三个实战案例",
    "",
    "**案例 1：写一封邮件**",
    "> 帮我写一封给客户的跟进邮件，语气礼貌但不过于正式，提醒他们上周的报价还有 3 天有效期",
    "",
    "**案例 2：翻译**",
    "> 把下面这段话翻译成英文：项目预计在六月底完成，届时我们会安排一次线上演示。",
    "",
    "**案例 3：头脑风暴**",
    "> 我要办一个 AI 主题的线上分享会，帮我 brainstorm 10 个吸引人的活动主题",
    "",
    "### 🔥 第四步：进阶技巧",
    "",
    "1. 用角色扮演提升质量：让 ChatGPT 扮演特定角色，回答会更有针对性",
    "   - 你是一个资深人力资源专家...",
    "   - 你是一个 10 年经验的 Python 开发者...",
    "",
    "2. 分步骤提问：复杂问题拆成小步骤，一一解决",
    "",
    "3. 追问和纠正：觉得回答不够好，直接说换一种方式或再具体一点",
    "",
    "4. 使用自定义指令：在设置里告诉 ChatGPT 你的身份和偏好，每次对话都会记住",
    "",
    "5. 利用对话历史：同一个对话里，ChatGPT 会记住上下文，可以持续深入",
  ],
  "deepseek-beginners": [
    "### 📝 第一步：注册",
    "",
    "1. 访问 chat.deepseek.com",
    "2. 点击注册，使用手机号（国内手机号完美支持）",
    "3. 输入验证码，设置密码",
    "4. 完成注册，直接进入对话界面",
    "",
    "> 🎉 **好消息**：DeepSeek 完全免费，无需绑定信用卡！",
    "",
    "### 🤔 第二步：体验核心功能",
    "",
    "**1. 文本对话**",
    "在输入框直接输入问题，DeepSeek 会用中文回答。它对中文的理解特别出色，是国内 AI 的佼佼者。",
    "",
    "**2. 上传文件**",
    "DeepSeek 支持上传 PDF、Word、Excel、PPT、图片等文件，可以帮你分析文档内容。",
    "",
    "**3. 联网搜索**",
    '点击输入框上方的"联网搜索"按钮，DeepSeek 就能获取最新信息。（默认不开启）',
    "",
    "### 🎯 第三步：实战案例",
    "",
    "**案例 1：分析 Excel 数据**",
    "上传一个 Excel 文件，说：帮我看一下这个表格的销售趋势，找出增长最快的月份",
    "",
    "**案例 2：写周报**",
    "> 帮我写一份这周的周报模板，我是产品经理，这周做了用户调研、原型设计和需求评审",
    "",
    "**案例 3：学习助手**",
    "> 我正在学 Python，解释一下什么是列表推导式，用生活中的例子类比",
    "",
    "### 🔥 第四步：进阶技巧",
    "",
    "1. 长文处理：DeepSeek 上下文窗口很大（1M tokens），可以一次性分析整本书",
    "2. 角色设定：告诉它你的身份，回答更精准",
    "3. 多轮对话：在同一个对话中持续深入话题",
    "4. 文件批量分析：可以上传多个文件一起分析",
  ],
  "claude-code": [
    "### 📝 第一步：安装",
    "",
    "**前置条件**：",
    "- Node.js v18+（终端运行 node -v 查看版本）",
    "- Git（终端运行 git --version 查看）",
    "- Anthropic 账号（console.anthropic.com）",
    "- API Key（在 Anthropic Console 生成）",
    "",
    "**安装命令**：",
    "```bash",
    "npm install -g @anthropic-ai/claude-code",
    "```",
    "",
    "**配置 API Key**：",
    "```bash",
    "export ANTHROPIC_API_KEY=sk-your-key-here",
    "# Windows PowerShell:",
    '$env:ANTHROPIC_API_KEY="sk-your-key-here"',
    "```",
    "",
    "### 🤔 第二步：第一个项目",
    "",
    "进入你的项目目录，运行：",
    "```bash",
    "cd my-project",
    "claude",
    "```",
    "",
    '看到 > 提示符就说明启动成功了。试试输入：',
    '> 帮我创建一个简单的 Express 服务器，监听 3000 端口',
    "",
    "Claude Code 会自动创建文件、安装依赖，一气呵成。",
    "",
    "### 🎯 第三步：实战案例",
    "",
    "**案例 1：添加新功能**",
    '> 给这个 Todo 应用添加一个按优先级排序的功能，优先级分高/中/低三档',
    "",
    "**案例 2：修 Bug**",
    '> 用户登录后看不到个人信息页面，帮我检查路由和权限逻辑',
    "",
    "**案例 3：写测试**",
    "> 为 src/utils/format.ts 中的函数写单元测试",
    "",
    "### 🔥 第四步：进阶技巧",
    "",
    "1. 多文件编辑：Claude Code 可以同时修改多个文件",
    "2. Git 集成：自动创建 git commit，每个改动都可追溯",
    "3. 终端命令：可以直接在对话里执行终端命令",
    "4. 项目理解：会自动读取项目结构，理解代码上下文",
    "5. 成本控制：在对话中查看 token 消耗，合理规划使用",
  ],
  "codex-beginners": [
    "### 📝 第一步：安装 Codex CLI",
    "",
    "**前置条件**：",
    "- Node.js v18+",
    "- OpenAI API Key",
    "",
    "**安装**：",
    "```bash",
    "npm install -g @openai/codex",
    "```",
    "",
    "**配置**：",
    "```bash",
    "export OPENAI_API_KEY=sk-your-key-here",
    "# 或者在项目根目录创建 .env 文件",
    "```",
    "",
    "### 🤔 第二步：开始使用",
    "",
    "```bash",
    "codex",
    "```",
    "",
    "这会启动 Codex CLI 交互模式。你可以用自然语言描述你想要的功能。",
    "",
    "试试：",
    '> 创建一个 Next.js 博客项目，包含首页、文章列表页和文章详情页',
    "",
    "### 🎯 第三步：实战案例",
    "",
    "**案例 1：数据分析脚本**",
    '> 写一个 Python 脚本，读取 sales.csv 文件，计算每月的销售额并生成柱状图',
    "",
    "**案例 2：API 开发**",
    '> 创建一个 Express API，包含用户注册、登录和获取用户信息三个接口',
    "",
    "**案例 3：前端组件**",
    '> 创建一个 React 文件上传组件，支持拖拽、预览、进度条',
    "",
    "### 🔥 第四步：进阶技巧",
    "",
    "1. 分步实现：复杂功能拆成多个步骤，每个步骤确认后再继续",
    "2. 代码审查：让 Codex 审查现有代码，找出潜在问题",
    "3. 重构优化：用自然语言描述你想怎么重构代码",
    "4. 多语言支持：支持 JavaScript、TypeScript、Python、Rust 等多种语言",
    "5. 集成测试：可以让 Codex 帮你写端到端测试",
  ],
  "prompt-engineering": [
    "### 🤔 什么是 Prompt？",
    "",
    "Prompt 就是你给 AI 的指令——你问什么，AI 就回答什么。但是，问法不同，答案质量天差地别。",
    "",
    "就像你去咖啡店：",
    '- ❌ "给我杯咖啡" → 得到什么全看店员心情',
    '- ✅ "一杯热的、中杯、少糖的燕麦拿铁" → 分毫不差',
    "",
    "Prompt 工程就是学会用精准的指令让 AI 输出你想要的答案。",
    "",
    "### 📝 核心原则：4S 法则",
    "",
    "**1. Specific（具体）**",
    '❌ "写一个方案"',
    '✅ "写一个面向 25-35 岁白领的健身 App 推广方案，预算 5 万，周期 1 个月"',
    "",
    "**2. Simple（简洁）**",
    "一条指令只做一件事。复杂需求拆成多轮对话。",
    "",
    "**3. Structure（结构化）**",
    "用清晰的格式组织你的要求：",
    '> 请用以下格式输出：',
    "> - 优点：列出 3 个",
    "> - 缺点：列出 2 个",
    "> - 建议：列出 2 个",
    "",
    "**4. Scenario（场景）**",
    "给 AI 设定角色和场景：",
    '> 你是一个 5 年经验的文案专家，擅长写吸引人的社交媒体文案...',
    "",
    "### 🎯 实战模板库",
    "",
    "**模板 1：角色扮演**",
    "> 你是一个 [身份]，擅长 [技能]。请帮我 [任务]。要求：[具体要求]。",
    "",
    "**模板 2：改写润色**",
    "> 请帮我改写下面这段话，风格：[正式/幽默/简洁/感人]，目标读者：[谁]，字数：[多少字]。",
    "",
    "**模板 3：分析总结**",
    "> 请分析下面这段内容的[关键观点/核心论据/主要问题]，用列表形式输出，每个点附带原文引用。",
    "",
    "### 🔥 进阶技巧",
    "",
    "1. Few-shot 示例：给出 2-3 个例子，AI 会更准确",
    "2. 思维链：让 AI 一步一步思考，复杂问题的准确率大幅提升",
    "3. 负向提示：告诉 AI 不要做什么",
    "4. 温度控制：creative 任务用高温度，精确任务用低温度",
    "5. 迭代优化：第一次不满意就继续追问，直到满意为止",
  ],
}

export function TutorialContent({ slug }: { slug: string }) {
  const [content, setContent] = useState<string[]>([])

  useEffect(() => {
    setContent(tutorialContentMap[slug] || ["教程内容更新中，敬请期待..."])
  }, [slug])

  if (content.length === 0) return null

  const renderLine = (line: string, index: number) => {
    if (line.startsWith("### ")) {
      return <h3 key={index} id={line.replace("### ", "").toLowerCase().replace(/\s+/g, "-")} className="text-lg font-bold mt-8 mb-3">{line.replace("### ", "")}</h3>
    }
    if (line.startsWith("## ")) {
      return <h2 key={index} className="text-xl font-bold mt-10 mb-4">{line.replace("## ", "")}</h2>
    }
    if (line.startsWith("# ")) {
      return <h1 key={index} className="text-2xl font-bold mt-12 mb-4">{line.replace("# ", "")}</h1>
    }
    if (line.startsWith("> ")) {
      return <blockquote key={index} className="border-l-4 border-primary/30 pl-4 py-1 my-3 text-muted-foreground italic">{line.replace(/^> /, "")}</blockquote>
    }
    if (line.startsWith("```")) {
      return null
    }
    if (line.startsWith("- ")) {
      return <li key={index} className="text-muted-foreground ml-4">{line.replace("- ", "")}</li>
    }
    if (/^\d+\./.test(line)) {
      return <li key={index} className="text-muted-foreground ml-4 list-decimal">{line.replace(/^\d+\.\s*/, "")}</li>
    }
    if (line.trim() === "") {
      return <div key={index} className="h-2" />
    }
    return <p key={index} className="text-muted-foreground leading-relaxed mb-2">{line}</p>
  }

  return (
    <div className="prose-custom">
      {content.map((line, index) => renderLine(line, index))}
    </div>
  )
}
